export const genres = [
  "Drum & Bass",
  "EDM",
  "House",
  "Melodic House & Techno",
  "Pop / Dance / Disco",
  "Tech House",
  "Techno",
  "Trance",
];

export const subGenres = [
  "Afro House",
  "Bass / Club",
  "Bass House",
  "Big Room",
  "Breaks / Breakbeat / UK Bass",
  "DJ Tools",
  "Dance / Electro Pop",
  "Deep House",
  "Drum & Bass",
  "Dubstep",
  "Electro House",
  "Electronica",
  "Funky House",
  "Future House",
  "Hard Dance / Hardcore",
  "Hard Techno",
  "Indie Dance",
  "Jackin House",
  "Leftfield House & Techno",
  "Mainstage",
  "Minimal / Deep Tech",
  "Nu Disco / Disco",
  "Organic House / Downtempo",
  "Progressive House",
  "Psy-Trance",
  "Trance (Main Floor)",
  "Trap / Future Bass",
  "Trap / Wave",
  "UK Garage / Bassline",
];

export const artists = [
  "&ME",
  "Adam Beyer",
  "Armin van Buuren",
  "ARTBAT",
  "Block & Crown",
  "Calvin Harris",
  "CamelPhat",
  "Catch & Release",
  "Chris Lake",
  "Claptone",
  "Crazibiza",
  "Cristoph",
  "David Guetta",
  "Dennis Cruz",
  "Dimitri Vegas",
  "Don Diablo",
  "Dubstep",
  "Eli Brown",
  "Enrico Sangiuliano",
  "Fedde Le Grand",
  "Ferreck Dawn",
  "FISHER (OZ)",
  "Green Velvet",
  "Hardwell",
  "Hot Since 82",
  "Innervisions",
  "Jay Lumen",
  "John Summit",
  "Josh Butler",
  "Layton Giordani",
  "Lissat",
  "Maceo Plex",
  "Mark Knight",
  "Martin Garrix",
  "Martin Ikin",
  "Nora En Pure",
  "Oliver Heldens",
  "Purple Disco Machine",
  "R3HAB",
  "Riva Starr",
  "Richard Grey",
  "Sander Van Doorn",
  "Solardo",
  "Sonny Fodera",
  "Stil Vor Talent",
  "Tiesto",
  "Tube & Berger",
  "UMEK",
  "Victor Ruiz",
  "W&W",
];

export const labels = [
  "1605",
  "8Bit",
  "Afterlife Records",
  "Anjunabeats",
  "Anjunadeep",
  "Armind (Armada)",
  "Atlantic Records UK",
  "Axtone Records",
  "Black Book Records",
  "Catch & Release",
  "Club Sweat",
  "Columbia (Sony)",
  "Cr2 Records",
  "Crosstown Rebels",
  "Defected",
  "Diynamic",
  "DIRTYBIRD",
  "DFTD",
  "DOORN RECORDS",
  "Drumcode",
  "Enormous Tunes",
  "Exploited",
  "Filth on Acid",
  "Glasgow Underground",
  "Hot Creations",
  "Innervisions",
  "Keinemusik",
  "Kittball",
  "Knee Deep In Sound",
  "Ministry of Sound Recordings",
  "Musical Freedom",
  "Noir Music",
  "PornoStar Records",
  "Prison Entertainment",
  "Protocol Recordings",
  "Repopulate Mars",
  "Relief",
  "Revealed Recordings",
  "Revealed Recordings (back catalog)",
  "Snatch! Records",
  "Sola",
  "SOLOTOKO",
  "SPINNIN' DEEP",
  "SPINNIN' RECORDS",
  "Stil Vor Talent",
  "Suara",
  "Tactical Records",
  "Terminal M",
  "Toolroom",
  "Truesoul",
  "Ultra",
];
